name: WFB-ng package builder for debian

on:
  push:
    branches: [ master, release-23.08 ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master, stable ]

jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        version: [11, 12]
        arch: [ "arm32v7", "arm64v8", "amd64", "mips64le", "s390x", "ppc64le"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: build package
        run: |
          curl -s -L https://github.com/svpcom/wfb-ng/releases/download/wifibroadcast-17.10/qemu-7.2.13-fixed.tar.gz | sudo tar xzv -C /
          make deb_docker DOCKER_SRC_IMAGE=${{ matrix.arch }}/debian:${{ matrix.version }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: wfb-ng-${{ github.ref_name }}-debian${{ matrix.version }}-${{ matrix.arch }}
          path: |
            deb_dist/*.deb
      - name: Output artifact URL
        run:  echo 'wfb-ng-${{ github.ref_name }}-debian${{ matrix.version }}-${{ matrix.arch }} ${{ steps.artifact-upload-step.outputs.artifact-url }}'
